name: Copy Database from stocks_data_management

on:
  schedule:
    # 9:17 AM to 9:59 AM IST (3:47 AM to 3:59 AM UTC)
    - cron: "47-59/5 3 * * 1-5"
    # 10:00 AM to 2:59 PM IST (4:00 AM to 8:59 AM UTC)
    - cron: "0-59/5 4-8 * * 1-5"
    # 3:00 PM to 3:32 PM IST (9:00 AM to 10:32 AM UTC)
    - cron: "0-32/5 9-10 * * 1-5"
  workflow_dispatch:

jobs:
  copy-database:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout train_rnn_models repository
      uses: actions/checkout@v3

    - name: Clone stocks_data_management repository
      run: |
        git clone https://github.com/chiragpalan/stocks_data_management.git stocks_repo

    - name: Copy Database File
      run: |
        cp stocks_repo/nifty50_data_v1.db .

    - name: Commit and Push Database File
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add nifty50_data_v1.db
        git commit -m "Update database file from stocks_data_management"
        git push https://x-access-token:${GH_PAT}@github.com/chiragpalan/test_v1.git
