name: Copy Database from stocks_data_management

on:
  schedule:
    - cron: "17-59/5 3 * * 1-5" # 9:17 AM to 9:59 AM IST
    - cron: "0-59/5 4-8 * * 1-5" # 10:00 AM to 2:59 PM IST
    - cron: "0-3/5 9 * * 1-5" # 3:00 PM to 3:33 PM IST
  workflow_dispatch:

jobs:
  copy-database:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout train_rnn_models repository
      uses: actions/checkout@v3

    - name: Clone stocks_data_management repository
      run: |
        git clone https://github.com/chiragpalan/stocks_data_management.git stocks_repo

    - name: Copy Database File
      run: |
        cp stocks_repo/nifty50_data_v1.db .

    - name: Commit and Push Database File
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add nifty50_data_v1.db
        git commit -m "Update database file from stocks_data_management"
        git push https://x-access-token:${GH_PAT}@github.com/chiragpalan/test_v1.git
