name: Join Tables

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    join-tables:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Set up Python
          uses: actions/setup-python@v2
          with:
              python-version: '3.8'

        - name: Install dependencies
          run: |
              python -m pip install --upgrade pip
              pip install pandas sqlite3

        - name: Run join tables script
          run: |
              python join_predictions.py

        - name: Commit and push changes
          run: |
              git config --global user.name 'github-actions'
              git config --global user.email 'github-actions@github.com'
              git add join_pred.db
              git commit -m 'Update joined tables'
              git push
          env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
