name: Predict RNN

on:
  schedule:
    - cron: "*/15 3-10 * * 1-5" # Every 15 mins between 9:15 AM and 3:30 PM IST Monday to Friday
  workflow_dispatch: # Allows manual trigger

jobs:
  predict:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run prediction script
      run: |
        mkdir -p predictions
        python predict_rnn.py
