name: Prediction Workflow

on:
  schedule:
    # 9:18 AM to 9:59 AM IST (3:48 AM to 4:29 AM UTC)
    - cron: "48-59/5 3 * * 1-5"
    # 10:00 AM to 2:59 PM IST (4:30 AM to 9:29 AM UTC)
    - cron: "0-59/5 4-9 * * 1-5"
    # 3:00 PM to 3:33 PM IST (9:30 AM to 10:03 AM UTC)
    - cron: "0-33/5 10 * * 1-5"
  workflow_dispatch:   # Manual trigger (optional)

jobs:
  predict_rnn:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run predict_rnn.py
        run: |
          python predict_rnn.py

      - name: Check if predictions.db exists
        run: |
          if [ -f "predictions/predictions.db" ]; then
            echo "Prediction database found."
            git config --global user.name "GitHub Actions"
            git config --global user.email "github-actions@github.com"
            git add predictions/predictions.db
            git commit -m "Update prediction database"
            git push
          else
            echo "No predictions.db file found, skipping commit"
          fi
