name: Prediction Workflow

on:
  schedule:
    # Run at every 15 minutes from 9:15 AM to 3:30 PM IST (every Monday to Friday)
    - cron: '15,30,45,0 3-9 * * 1-5'
  workflow_dispatch:

jobs:
  predict_rnn:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run predict_rnn.py
        run: |
          python predict_rnn.py

      - name: Check if predictions.db exists
        run: |
          if [ -f "predictions/predictions.db" ]; then
            echo "Prediction database found."
            git config --global user.name "GitHub Actions"
            git config --global user.email "github-actions@github.com"
            git add predictions/predictions.db
            git commit -m "Update prediction database"
            git push
          else
            echo "No predictions.db file found, skipping commit"
          fi
