name: Predict RNN

on:
  schedule:
    - cron: "*/15 3-10 * * 1-5" # Runs every 15 minutes from 9:15 AM to 3:30 PM IST Monday to Friday
  workflow_dispatch: # Allows manual trigger

jobs:
  predict:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run prediction script
      run: |
        mkdir -p predictions
        python predict_rnn.py

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add predictions/
        git commit -m "Update prediction database"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
